os: windows
language: sh

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
# 5.6
#    - php: '5.6'
#      env: TEST_CONFIG="phpunit.xml"
# 7.1
    - php: '7.1'
      env: TEST_CONFIG="phpunit.xml"

# test only master, stable branches and pull requests
branches:
  only:
    - master
    - /^\d.\d+$/

before_install:
  - choco install php --version 7.1.29
  - export PATH=/c/tools/php71

install:
  -  travis_retry composer install --no-progress --no-interaction --prefer-dist "${COMPOSER_FLAGS}"

script:
  - php -d memory_limit=-1 ./vendor/bin/phpunit -c "${TEST_CONFIG}"

# reduce depth (history) of git checkout
git:
  depth: 30
