services:
    ezpublish.console.command.regenerate_url_aliases:
        class: eZ\Bundle\EzPublishCoreBundle\Command\RegenerateUrlAliasesCommand
        arguments:
            - '@=service("ezpublish.api.repository").getPermissionResolver()'
            - '@ezpublish.api.service.user'
            - '@ezpublish.api.service.location'
            - '@ezpublish.api.service.content'
            - '@ezpublish.api.service.url_alias'
            - '@?logger'
        tags:
            - { name: console.command }
